version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credit_db
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # credit-application-service:
  #   build: ./credit-application-service
  #   container_name: credit-application-service
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/credit_db
  #   depends_on:
  #     - postgres
  #     - kafka
  #     - rabbitmq

  # credit-processing-service:
  #   build: ./credit-processing-service
  #   container_name: credit-processing-service
  #   depends_on:
  #     - kafka
  #     - rabbitmq
