spring.application.name: "credit-application-service"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditapp
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: credit-application-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest